# Generated by Django 2.2.4 on 2019-08-02 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_answerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_answerer_article', to=settings.AUTH_USER_MODEL, verbose_name='最后回复者'),
        ),
        migrations.AddField(
            model_name='article',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Node', verbose_name='所属节点'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Source', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_article', to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_article', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
