# Generated by Django 2.2.4 on 2019-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('0', '女'), ('1', '男'), ('2', '未填写')], default='未知', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
