"""
Django settings for django2 project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from __future__ import absolute_import  # 解决命名问题
import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 自定义目录 apps, apps_extra
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
sys.path.insert(0, os.path.join(BASE_DIR, "apps_extra"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(!*9a@##(h3ci(yh4b+cqrg!q1pqfb8uo7&)e(^5^rh9y7dj2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = 'users.UserProfile'

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'apps.users',
    'apps.blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # {{ MEDIA_URL }}无法显示图片
            ],
        },
    },
]

WSGI_APPLICATION = 'django2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static').replace('\\', '/'),
]
STATIC_ROOT = 'static_root/'  # 只有右边斜杠

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')

TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)

# ckeditor
CKEDITOR_CONFIGS = {
    'language': 'zh-cn',
    'awesome_ckeditor': {
        'toolbar': 'full',
    },
}

CKEDITOR_UPLOAD_PATH = 'ckeditor/'  # 他的目录相对与 media root 就是 media root + CKEDITOR_UPLOAD_PATH 不能写成"/uploads
# CKEDITOR_UPLOAD_PATH = ''  # 图片ckeditor文件上传路径, 这里使用七牛云存储，不填
CKEDITOR_JQUERY_URL = '//cdn.bootcss.com/jquery/1.11.3/jquery.min.js'
# https://pillow.readthedocs.io/en/stable/installation.html
CKEDITOR_IMAGE_BACKEND = 'pillow'  # pip install Pillow
# DEFAULT_FILE_STORAGE = 'blog.ckeditor_storage.StorageObject'

# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.exmail.qq.com'  # SMTP地址
# EMAIL_HOST = 'hwsmtp.exmail.qq.com'  # 海外用户SMTP地址
# qq 普通邮箱发送邮件服务器：smtp.qq.com，使用SSL，端口号587
# 腾讯企业邮-IMAP协议/POP3/SMTP协议
# 发送邮件服务器：smtp.exmail.qq.com ，使用SSL，端口号465
# 海外发送邮件服务器：hwsmtp.exmail.qq.com ，使用SSL，端口号465
EMAIL_PORT = 465  # SMTP发送端口
EMAIL_HOST_USER = ''  # 自己的邮箱
EMAIL_HOST_PASSWORD = ''  # 我的邮箱密码
EMAIL_SUBJECT_PREFIX = '博客管理系统'  # 为邮件Subject-line前缀,默认是'[django]'
# EMAIL_USE_TLS = True  # 与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false。与SSL是互相排斥的。
EMAIL_USE_SSL = True  # 与SMTP服务器通信时，是否启动SSl链接(安全链接)。默认是false ,腾讯用SSL

# SMTPSenderRefused at /admin/password reset/
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # use when Debug

# simpleUI
SIMPLEUI_LOGO = '/static/images/joyo_icon.png'  # 管理后台log, 本地
# SIMPLEUI_LOGO = 'http://img.zhuoqun.info/joyo_icon.png'  # 管理后台log, 本地
SIMPLEUI_HOME_TITLE = '博客后台管理系统'  # 不启作用
SIMPLEUI_HOME_ICON = ''  # 首页图标
SIMPLEUI_INDEX = 'https://xieboke.net'  # 首页跳转地址
